# Generated by Django 4.2.7 on 2023-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dui',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Edad',
            field=models.IntegerField(),
        ),
    ]
