# Generated by Django 4.2.7 on 2023-11-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_area_descripcion_alter_cliente_dui_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nombre_Area',
            field=models.CharField(max_length=80),
        ),
    ]
